project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "YOUR PROJECT TITLE"
  author:
    - Jiwon Bae (jb5234)
    - Hillary Rodriguez (hnr2112)
  repo-url: https://github.com/MatildaBae/outages_report.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


